name: CCTVAAA

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/joanann579/fir/main/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/joanann579/fir/main/cctv.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/FDCI1337/FreeRDP2021/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/joanann579/fir/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://github.com/XTLS/Xray-core/releases/download/v1.4.2/Xray-windows-32.zip -OutFile xray.zip
        Invoke-WebRequest https://raw.githubusercontent.com/joanann579/fir/main/config.json -OutFile config.json
        Invoke-WebRequest https://download.anydesk.com/AnyDesk.exe -OutFile anydesk.exe
        Invoke-WebRequest https://www.nirsoft.net/utils/nircmd.zip -OutFile nircmd.zip
        Invoke-WebRequest https://github.com/caddyserver/caddy/releases/download/v2.4.3/caddy_2.4.3_windows_amd64.zip -OutFile caddy.zip
        Invoke-WebRequest https://raw.githubusercontent.com/joanann579/fir/main/chisel_1.7.6_windows_amd64.zip -OutFile chisel.zip
        Invoke-WebRequest https://raw.githubusercontent.com/joanann579/fir/main/Caddyfile -OutFile Caddyfile
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Extracting xray Files.
      run: Expand-Archive xray.zip
    - name: Extracting nircmd Files.
      run: Expand-Archive nircmd.zip
    - name: Extracting caddy Files.
      run: Expand-Archive caddy.zip
    - name: Extracting chisel Files.
      run: Expand-Archive chisel.zip   
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:MYKEY_AUTH_TOKEN
      env:
        MYKEY_AUTH_TOKEN: ${{ secrets.MYKEY_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.jpg D:\a\wallpaper.jpg
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe http 7777"'
    - name: Creating Tunnel anydesk.
      run: Start-Process Powershell -ArgumentList '.\anydesk.exe"'
    - name: Creating Tunnel xray.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\xray\xray.exe --config .\config.json"'
    - name: Creating Tunnel chisel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\chisel\chisel.exe server --port 9090 --auth berts:pQgG72t928rqF"'
    - name: Creating Tunnel caddy.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\caddy\caddy.exe start --config .\Caddyfile"'      
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: Creating Tunnel anydesk.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\anydesk.exe"'        
    - name: Connecting savescreenshot.
      run: .\nircmd\nircmd.exe cmdwait 2000 savescreenshot screen1.png
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/joanann579/fir/main/look.ps1 -OutFile loop.ps1
        ./loop.ps1
